name: Deployment dev

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: ubuntu-latest
        description: Runner tag for workflow
      timeout_minutes:
        required: false
        type: number
        default: 30
        description: Timeout for workflow
      image_tag:
        required: true
        type: string
        description: Image tag for docker artifact
      image_name:
        required: true
        type: string
        description: Image name for docker artifact
      app_name:
        required: false
        type: string
        description: |
          Application name. This is the release name in versions.yml in helm-configuration repo.
          If your release is named the same as your docker image, there's no need to set app_name
          (if you don't set app_name, image_name will be used as release name).
          But if your release name is different (e.g. you use the same image for multiple releases),
          then you must set app_name.
      helm_repo_branch:
        required: false
        type: string
        default: main
        description: Branch of helm-configuration repo to use
    secrets:
      app_id:
        required: true
      app_private_key:
        required: true
      role_to_assume:
        required: true
      aws_region:
        required: true
      eks_cluster_name:
        required: true

jobs:
  deploy:
    runs-on: "${{ inputs.runs_on }}"
    steps:
      - name: Generate a token
        id: generate-token
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.app_id }}
          private_key: ${{ secrets.app_private_key }}

      - name: Checkout helm-configuration repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: propeller-heads/helm-configuration
          ref: "${{ inputs.helm_repo_branch }}"
          token: ${{ steps.generate-token.outputs.token }}

      - name: Install yq
        run: sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq

      - name: Install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          verbose: false
          arch: amd64
          rootdir: ""
          workdir: ""

      - name: Assume role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "${{ secrets.role_to_assume }}"
          audience: sts.amazonaws.com
          aws-region: "${{ secrets.aws_region }}"

      - name: Setup kubeconfig
        run: aws eks update-kubeconfig --name "${{ secrets.eks_cluster_name }}" --region "${{ secrets.aws_region }}"

      - name: Install helmwave
        uses: helmwave/setup-action@v0.3.0
        with:
          version: 0.37.1

      - name: Replace release version
        run: |
          yq eval '.${{ inputs.app_name || inputs.image_name }}.tag="${{ inputs.image_tag }}"' -i helmwave/dev/versions.yml
          cat helmwave/dev/versions.yml

      - name: Deploy app uses helmwave
        run: |
          cd helmwave/dev
          helmwave yml
          helmwave up --build
        env:
          HELMWAVE_TAGS: ${{ inputs.app_name }}
          HELMWAVE_KUBEDOG_ENABLED: true
