name: Deployment dev

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: ubuntu-latest
        description: Runner tag for workflow
      timeout_minutes:
        required: false
        type: number
        default: 30
        description: Timeout for workflow
      slack_webhook_url:
        required: true
        type: string
        description: Slack webhook url
      workflow_url:
        required: true
        type: string
        description: Workflow url
    secrets:
      app_id:
        required: true
      app_private_key:
        required: true
      role_to_assume:
        required: true
      aws_region:
        required: true
      eks_cluster_name:
        required: true

env:
  SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
  WORKFLOW_URL: ${{ inputs.workflow_url }}
  ENVIRONMENT: dev

jobs:
  deploy:
    runs-on: "${{ inputs.runs_on }}"
    steps:
      - name: Generate a token
        id: generate-token
        uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc
        with:
          app_id: ${{ secrets.app_id }}
          private_key: ${{ secrets.app_private_key }}

      - name: Checkout helm-configuration repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Install-aws-cli
        uses: unfor19/install-aws-cli-action@e8b481e524a99f37fbd39fdc1dcb3341ab091367
        with:
          version: 2
          verbose: false
          arch: amd64
          rootdir: ""
          workdir: ""

      - name: Assume role
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722
        with:
          role-to-assume: "${{ secrets.role_to_assume }}"
          audience: sts.amazonaws.com
          aws-region: "${{ secrets.aws_region }}"

      - name: Setup kubeconfig
        run: aws eks update-kubeconfig --name "${{ secrets.eks_cluster_name }}" --region "${{ secrets.aws_region }}"

      - name: Install helmwave
        uses: helmwave/setup-action@a2b84aea3434be147501a53655b9fec902532533
        with:
          version: 0.37.1

      - name: Slack Notification
        run: bash scripts/slack-notify.sh started
        env:
          WORKFLOW_STATUS: ":large_blue_square: In Progress"

      - name: Deploy app uses helmwave
        run: |
          cd helmwave/dev
          helmwave yml
          helmwave up --build
        env:
          HELMWAVE_KUBEDOG_ENABLED: true

      - name: Slack Notification
        if: success()
        run: bash scripts/slack-notify.sh succeed
        env:
          WORKFLOW_STATUS: ":large_green_square: Completed"

      - name: Slack Notification
        if: failure()
        run: bash scripts/slack-notify.sh failed
        env:
          WORKFLOW_STATUS: ":large_red_square: Failed"
