name: "Deployment dev"

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: ubuntu-latest
        description: "Runner tag for workflow"
      timeout_minutes:
        required: false
        type: number
        default: 30
        description: "Timeout for workflow"
      role_to_assume:
        required: false
        type: string
        default: "arn:aws:iam::827659017777:role/github-actions"
        description: "ARN role to assume"
      aws_region:
        required: false
        type: string
        default: "eu-central-1"
        description: "Default AWS region"
      eks_cluster_name:
        required: true
        type: string
        default: "dr-eks-prod"
        description: "EKS cluster name"
      image_tag:
        required: true
        type: string
        description: "Image tag for docker artifact"
      app_name:
        required: true
        type: string
        description: "Application name"
      repository_url:
        required: false
        type: string
        default: "827659017777.dkr.ecr.eu-central-1.amazonaws.com"
        description: "Repository URL"
      namespace:
        required: true
        type: string
        description: "Namespace name"

jobs:
  deploy:
    runs-on: '${{ inputs.runs_on }}'
    steps:
      - name: "Checkout helmwave values"
        uses: actions/checkout@v4
        with:
          repository: "propeller-heads/ci-cd-templates-dont-remove"
          ref: 'main'
          token: ${{ steps.app-token.outputs.token }}
          path: './tmp/'

      - name: "Install-aws-cli"
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          verbose: false
          arch: amd64
          rootdir: ""
          workdir: ""

      - name: "Assume role"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "${{ inputs.role_to_assume }}"
          audience: sts.amazonaws.com
          aws-region: "${{ inputs.aws_region }}"

      - name: "Setup kubeconfig"
        run: aws eks update-kubeconfig --name "${{ inputs.eks_cluster_name }}" --region "${{ inputs.aws_region }}"

      - name: "Install helmwave"
        uses: helmwave/setup-action@v0.3.0
        with:
          version: "0.37.1"

      - name: "Deploy app uses helmwave"
        run: |
              cd ./tmp/helmwave/dev
              helmwave yml
              helmwave up --build
        env:
          REPOSITORY_URL: "${{ inputs.repository_url }}/${{ inputs.app_name }}"
          IMAGE_TAG: "${{ inputs.image_tag }}"
          APP_NAME: "${{ inputs.app_name }}"
          NAMESPACE: "${{ inputs.namespace }}"
          HELMWAVE_KUBEDOG_ENABLED: true
