name: Formatting python

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: ubuntu-latest
      timeout_minutes:
        required: false
        type: number
        default: 15
      python_version:
        required: false
        type: string
        default: 3.9
      black_options:
        required: false
        type: string
        default: "--check --skip-magic-trailing-comma"
      black_src:
        required: false
        type: string
      black_version:
        required: false
        type: string
        default: "21.5b2"
      black_jupyter:
        required: false
        type: string
        default: false

jobs:
  formatting-python:
    runs-on: "${{ inputs.runs_on }}"
    timeout-minutes: "${{ inputs.timeout_minutes }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "${{ inputs.python_version }}"
          cache: 'pip'

      - name: black Lint
        uses: psf/black@stable
        with:
          options: "${{ inputs.black_options }}"
          src: "${{ inputs.black_src }}"
          jupyter: "${{ inputs.black_jupyter }}"
          version: "${{ inputs.black_version }}"

      - name: Documentation Check
        run: |
            interrogate
