name: Formatting python

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: ubuntu-latest
      timeout_minutes:
        required: false
        type: number
        default: 15
      python_version:
        required: false
        type: string
        default: 3.9
      black_options:
        required: false
        type: string
        default: "--check --skip-magic-trailing-comma"
      black_src:
        required: false
        type: string
      black_version:
        required: false
        type: string
      black_jupyter:
        required: false
        type: string
        default: false
      black_summary:
        required: false
        type: string
        default: false
      black_use_pyproject:
        required: false
        type: string
        default: true

jobs:
  formatting-python:
    runs-on: "${{ inputs.runs_on }}"
    timeout-minutes: "${{ inputs.timeout_minutes }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "${{ inputs.python_version }}"
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements_dev.txt

      - name: Black Formatting
        run: |
          black ./defibot --check --skip-magic-trailing-comma

      - name: Documentation Check
        run: |
          interrogate
