on:
  pull_request:
    branches:
      - main

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: actionlint
      uses: raven-actions/actionlint@v2
      with:
        shellcheck: false
