on:
  push:
    branches:
      - ci/linters
#  pull_request:
#    branches:
#      - main

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
    - name: actionlint
      uses: raven-actions/actionlint@v2
      with:
        files: "./.github/workflows/*.yaml"
