on:
  pull_request:
    branches:
      - main

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    - name: actionlint
      uses: raven-actions/actionlint@01fce4f43a270a612932cb1c64d40505a029f821
      with:
        shellcheck: false
