name: Promote to production

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"
      image_tag:
        required: true
        type: string
        description: "Image tag for production"
      app_name:
        required: true
        type: string
        description: "Application name"
      assignees:
        required: false
        type: string
        description: "PR assignees"
      reviewers:
        required: false
        type: string
        description: "PR reviewers"
    secrets:
      gh_token:
        required: true


jobs:
  build:
    runs-on: '${{ inputs.runs_on }}'
    steps:
      - name: Install yq
        run: sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq

      - name: "Checkout ci/cd templates"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: "propeller-heads/ci-cd-templates-dont-remove"
          ref: "main"
          token: "${{ secrets.gh_token }}"

      - name: "Replace release version"
        run: | 
          yq eval '.${{ inputs.app_name }}.tag="${{ inputs.image_tag }}"' -i helmwave/prod/versions.yml

      - name: "Create pull request"
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Updated image version ${{ inputs.image_tag }} for application ${{ inputs.app_name }}"
          add-paths: | 
            helmwave/prod/versions.yml
          token: "${{ secrets.gh_token }}"
          branch: "production-release-${{ inputs.app_name }}-${{ inputs.image_tag }}"
          title: "Automated PR from repository ${{ inputs.app_name }}"
          delete-branch: true
          body: |
            This PR was created automatically by promote-to-production workflow from [${{ inputs.app_name }}](https://github.com/propeller-heads/${{ inputs.app_name }}) repository.
            - Updated image tag for ${{ inputs.app_name }} to ${{ inputs.image_tag }}.
          assignees: "${{ inputs.assignees }}"
          reviewers: "${{ inputs.reviewers }}"
