name: Release

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: ubuntu-latest
      timeout_minutes:
        required: false
        type: number
        default: 30
    secrets:
      gh_token:
        required: true
    outputs:
      next_release_version:
        value: ${{ jobs.release.outputs.NEXT_RELEASE_VERSION }}

jobs:
  release:
    name: release
    runs-on: "${{ inputs.runs_on }}"
    outputs:
      NEXT_RELEASE_VERSION: ${{ steps.semantic.outputs.NEXT_RELEASE_VERSION }}
    steps:
      - name: Install git
        run: sudo apt update && sudo apt install -y git

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1

      - name: Update NPM version (remove in future)
        run: npm i -g npm@10.5.0

      - name: Install dependencies
        run: npm install --save-dev  semantic-release@23.0.2 @semantic-release/changelog@6.0.3 @semantic-release/git@10.0.1 conventional-changelog-conventionalcommits@7.0.2 conventional-changelog-eslint@5.0.0 @semantic-release/exec@6.0.3 --legacy-peer-deps

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Semantic release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
        run: npx semantic-release

      - name: Validate Release
        env:
          NEXT_RELEASE_VERSION: ${{ steps.semantic.outputs.NEXT_RELEASE_VERSION }}
        run: |
          if [ -z "$NEXT_RELEASE_VERSION" ]; then
            echo "Error: Empty release, exiting..."
            exit 1
          else
            echo "Release version is: $NEXT_RELEASE_VERSION"
          fi
