name: Build verify

on:
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
        default: ubuntu-latest
      cache:
        required: false
        type: boolean

jobs:
  build-and-push:
    runs-on: '${{ inputs.runs_on }}'
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Verify build"
        run: | 
          echo "Verify build"
